version: '3.0'

networks:
  cinet:
    driver: bridge

volumes:
  postgresql:

services:

  jenkins:
    image: dpal/docker-jenkins-mobile-ci
    ports:
      - 8080:8080
      - 50000:50000
    networks:
      - cinet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker
      - ./data/jenkins:/var/jenkins_home
    restart: always
    depends_on:
      - sonarqube

  sonarqube:
    image: dpal/docker-sonarqube-mobile-ci:1.2.0
    ports:
      - 9000:9000
    networks:
      - cinet
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - ./data/sonarqube/conf:/opt/sonarqube/conf
      - ./data/sonarqube/data:/opt/sonarqube/data
      - ./data/sonarqube/extensions:/opt/sonarqube/extensions
      - ./data/sonarqube/logs:/opt/sonarqube/logs
    restart: always
    depends_on:
      - db

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:6.16.0
    ports:
     - 8081:8081
    networks:
     - cinet
    volumes:
     - ./data/artifactory:/var/opt/jfrog/artifactory
    restart: always
    
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    networks:
      - cinet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - ./data/postgresql:/var/lib/postgresql/data
    restart: always

