version: '3.0'

networks:
  cinet:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  postgresql:
  postgresql_data:
  jenkins_data:
    driver: local

services:

  jenkins:
    image: dpal/docker-jenkins-mobile-ci
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - cinet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker
      - jenkins_data:/var/jenkins_home
    depends_on:
      - sonarqube

  sonarqube:
    image: dpal/docker-sonarqube-mobile-ci
    ports:
      - "9000:9000"
    networks:
      - cinet
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions

  db:
    image: postgres
    networks:
      - cinet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data


